/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int NEWVAR = 9;
  /** RegularExpression Id. */
  int PV = 10;
  /** RegularExpression Id. */
  int TIPO = 11;
  /** RegularExpression Id. */
  int OPENPAR = 12;
  /** RegularExpression Id. */
  int CLOSEPAR = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int THEN = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int REPEAT = 17;
  /** RegularExpression Id. */
  int UNTIL = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int SYSTEMOUTPUT = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int FUNC = 23;
  /** RegularExpression Id. */
  int CHAR = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int NUM = 26;
  /** RegularExpression Id. */
  int FACAO_OPCIONAL = 27;
  /** RegularExpression Id. */
  int EXP_OPCIONAL = 28;
  /** RegularExpression Id. */
  int CHARORDIGIT = 29;
  /** RegularExpression Id. */
  int FINALSUBLINHADO = 30;
  /** RegularExpression Id. */
  int TOKEN_ID = 31;
  /** RegularExpression Id. */
  int TOKEN_NUMLITERAL = 32;
  /** RegularExpression Id. */
  int OP = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "\"newVar\"",
    "\";\"",
    "<TIPO>",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"repeat\"",
    "\"until\"",
    "\"return\"",
    "\"System.output\"",
    "\"true\"",
    "\"false\"",
    "\"func\"",
    "<CHAR>",
    "<DIGIT>",
    "<NUM>",
    "<FACAO_OPCIONAL>",
    "<EXP_OPCIONAL>",
    "<CHARORDIGIT>",
    "<FINALSUBLINHADO>",
    "<TOKEN_ID>",
    "<TOKEN_NUMLITERAL>",
    "<OP>",
    "\"=\"",
    "\",\"",
  };

}
